apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: pm-tp-infrastructure
  namespace: fleet-default
spec:
  repo: https://github.com/TransPerfectCloudDevOps/pm-tp-infrastructure.git
  branch: main
  paths:
    - .         # Main infrastructure (cert-manager installs its own CRDs)
  # No targets specified here - Fleet will use fleet.yaml in the repo
  # which defines targets for dev/staging/prod with proper values files
  pollingInterval: 120s
  # Allow Fleet to access Helm chart repositories for dependencies
  helmRepoURLRegex: "https://.*"
