apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: pm-tp-infrastructure
  namespace: fleet-default
spec:
  repo: https://github.com/TransPerfectCloudDevOps/pm-tp-infrastructure.git
  branch: main
  paths:
    - /crds      # CRDs bundle - deployed first
    - /          # Main infrastructure - depends on CRDs
  targets:
    - clusterSelector: {}
  pollingInterval: 120s
  # Allow Fleet to access Helm chart repositories for dependencies
  helmRepoURLRegex: "https://.*"
