apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: pm-tp-infrastructure
  namespace: fleet-default
spec:
  repo: https://github.com/TransPerfectCloudDevOps/pm-tp-infrastructure.git
  branch: main
  paths:
    - crds      # CRDs bundle - deployed first (no leading slash)
    - .         # Main infrastructure - depends on CRDs (current directory)
  targets:
    - name: infra
      clusterSelector:
        matchLabels:
          env: staging
      namespace: pm-tp-infra
  pollingInterval: 120s
  # Allow Fleet to access Helm chart repositories for dependencies
  helmRepoURLRegex: "https://.*"
