{{- if .Values.harbor.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harbor-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: harbor.rancher-poc.1.todevopssandbox.com
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-harbor-core
            port:
              number: 80
      - path: /service/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-harbor-core
            port:
              number: 80
      - path: /v2/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-harbor-core
            port:
              number: 80
      - path: /chartrepo/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-harbor-core
            port:
              number: 80
      - path: /c/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-harbor-core
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-harbor-portal
            port:
              number: 80
  tls:
  - hosts:
    - harbor.rancher-poc.1.todevopssandbox.com
    secretName: harbor-tls-secret
{{- end }}