{{- if and .Values.tidb.enabled .Values.tidbCluster.enabled }}
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: {{ .Release.Name }}-tidb
  namespace: {{ .Release.Namespace }}
spec:
  version: v7.5.1
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: {{ .Values.tidbCluster.pd.replicas | default 3 }}
    requests:
      storage: {{ .Values.tidbCluster.pd.storage | default "10Gi" }}
    config: {}
    {{- with .Values.tidbCluster.pd.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    replicas: {{ .Values.tidbCluster.tikv.replicas | default 3 }}
    requests:
      storage: {{ .Values.tidbCluster.tikv.storage | default "50Gi" }}
    config:
      storage:
        reserve-space: "0MB"
      rocksdb:
        max-open-files: 256
      raftdb:
        max-open-files: 256
    {{- with .Values.tidbCluster.tikv.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: {{ .Values.tidbCluster.tidb.replicas | default 2 }}
    service:
      type: ClusterIP
    config: {}
    {{- with .Values.tidbCluster.tidb.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
