# Staging Environment - Moderate Resources
# HA configuration, production-like setup

# TiDB Operator
# The operator manages TiDB clusters. The actual TiDB cluster is created separately.
tidb:
  enabled: true
  chart:
    repo: https://charts.pingcap.org/
    name: tidb-operator
    version: "1.5.0"
  values:
    # Disable scheduler - it has config compatibility issues
    scheduler:
      create: false
    # Minimal resources for staging
    controllerManager:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

# TiDB Cluster - Staging configuration with reduced resources
tidbCluster:
  enabled: true
  pd:
    replicas: 3
    storage: "10Gi"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  tikv:
    replicas: 3
    storage: "50Gi"
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi
  tidb:
    replicas: 2
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi

# Valkey
valkey:
  enabled: true
  chart:
    repo: https://valkey.io/valkey-helm/
    name: valkey
    version: "0.7.0"
  values:
    architecture: replication
    auth:
      enabled: true
      password: "changeme123"
    master:
      persistence:
        size: 10Gi
    replica:
      replicaCount: 2
      persistence:
        size: 10Gi

# MinIO
minio:
  enabled: true
  chart:
    repo: https://charts.min.io/
    name: minio
    version: "5.x.x"
  values:
    mode: distributed
    replicas: 4
    drivesPerNode: 1
    persistence:
      size: 50Gi
    rootUser: admin
    rootPassword: "changeme123"
    buckets:
      - name: pm-tp-files
        policy: none

# NATS
nats:
  enabled: true
  chart:
    repo: https://nats-io.github.io/k8s/helm/charts/
    name: nats
    version: "1.x.x"
  values:
    nats:
      jetstream:
        enabled: true
        fileStore:
          pvc:
            size: 20Gi
    cluster:
      enabled: true
      replicas: 3

# OpenSearch - Search Engine
# Temporarily disabled - requires vm.max_map_count=262144 on nodes
opensearch:
  enabled: false
  chart:
    repo: https://opensearch-project.github.io/helm-charts/
    name: opensearch
    version: "2.x.x"
  values:
    replicas: 3
    minimumMasterNodes: 2
    persistence:
      size: 30Gi
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi

# Keycloak - Identity and Access Management
keycloak:
  enabled: true
  chart:
    repo: https://charts.bitnami.com/bitnami
    name: keycloak
    version: "21.1.2"  # Latest stable
  values:
    # Production mode
    production: true
    # Admin user
    auth:
      adminUser: admin
      adminPassword: "changeme123"
      # Database config
      database: mysql
      databaseHost: pm-tp-infra-tidb-tidb.pm-tp-staging.svc
      databasePort: 4000
      databaseName: keycloak
      databaseUser: keycloak
      databasePassword: "keycloak_secure_password_123"
    # HTTP settings
    http:
      relativePath: /auth
    # Disable hostname strict for dev
    proxy: edge
    # Resources
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

# Prometheus
prometheus:
  enabled: true
  chart:
    repo: https://prometheus-community.github.io/helm-charts
    name: prometheus
    version: "25.x.x"
  values:
    server:
      retention: 15d
      persistentVolume:
        size: 30Gi
    alertmanager:
      enabled: true

# Grafana
grafana:
  enabled: true
  chart:
    repo: https://grafana.github.io/helm-charts
    name: grafana
    version: "7.x.x"
  values:
    adminUser: admin
    adminPassword: "changeme123"
    persistence:
      enabled: true
      size: 10Gi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-server
            isDefault: true
