# Staging Environment - Moderate Resources
# HA configuration, production-like setup

# TiDB
# Temporarily disabled - has issues, enable after basics are working
tidb:
  enabled: false
  chart:
    repo: https://charts.pingcap.org/
    name: tidb-operator
    version: "1.5.0"
  values:
    pd:
      replicaCount: 3
      persistence:
        size: 10Gi
    tikv:
      replicaCount: 3
      persistence:
        size: 50Gi
    tidb:
      replicaCount: 2

# Valkey
valkey:
  enabled: true
  chart:
    repo: https://valkey.io/valkey-helm/
    name: valkey
    version: "0.7.0"
  values:
    architecture: replication
    auth:
      enabled: true
      password: "changeme123"
    master:
      persistence:
        size: 10Gi
    replica:
      replicaCount: 2
      persistence:
        size: 10Gi

# MinIO
minio:
  enabled: true
  chart:
    repo: https://charts.min.io/
    name: minio
    version: "5.x.x"
  values:
    mode: distributed
    replicas: 4
    drivesPerNode: 1
    persistence:
      size: 50Gi
    rootUser: admin
    rootPassword: "changeme123"
    buckets:
      - name: pm-tp-files
        policy: none

# NATS
nats:
  enabled: true
  chart:
    repo: https://nats-io.github.io/k8s/helm/charts/
    name: nats
    version: "1.x.x"
  values:
    nats:
      jetstream:
        enabled: true
        fileStore:
          pvc:
            size: 20Gi
    cluster:
      enabled: true
      replicas: 3

# OpenSearch - Search Engine
# Temporarily disabled - requires vm.max_map_count=262144 on nodes
opensearch:
  enabled: false
  chart:
    repo: https://opensearch-project.github.io/helm-charts/
    name: opensearch
    version: "2.x.x"
  values:
    replicas: 3
    minimumMasterNodes: 2
    persistence:
      size: 30Gi
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi

# Keycloak
# Temporarily disabled - will re-enable after TiDB is configured
keycloak:
  enabled: false
  chart:
    repo: https://codecentric.github.io/helm-charts
    name: keycloakx
    version: "7.1.4"
  values:
    replicas: 2
    # Use H2 embedded database (not for production, just for staging testing)
    command:
      - "/opt/keycloak/bin/kc.sh"
    args:
      - "start-dev"
      - "--http-port=8080"
    extraEnv: |
      - name: KEYCLOAK_ADMIN
        value: "admin"
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: "changeme123"

# Prometheus
prometheus:
  enabled: true
  chart:
    repo: https://prometheus-community.github.io/helm-charts
    name: prometheus
    version: "25.x.x"
  values:
    server:
      retention: 15d
      persistentVolume:
        size: 30Gi
    alertmanager:
      enabled: true

# Grafana
grafana:
  enabled: true
  chart:
    repo: https://grafana.github.io/helm-charts
    name: grafana
    version: "7.x.x"
  values:
    adminUser: admin
    adminPassword: "changeme123"
    persistence:
      enabled: true
      size: 10Gi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-server
            isDefault: true
