# Traefik Fleet Bundle
# Deploys Traefik ingress controller with CRDs
# This deploys before the main infrastructure bundle

defaultNamespace: traefik-system

# Deploy to all environments
targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
    defaultNamespace: traefik-system
    helm:
      valuesFiles:
        - ../dev/traefik-values.yaml

  - name: staging
    clusterSelector:
      matchLabels:
        env: staging
    defaultNamespace: traefik-system
    helm:
      valuesFiles:
        - ../staging/traefik-values.yaml

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
    defaultNamespace: traefik-system
    helm:
      valuesFiles:
        - ../prod/traefik-values.yaml

# Use the official Traefik Helm chart
helm:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  version: "~26.0.0"
  releaseName: traefik
  timeoutSeconds: 600

# Ensure CRDs are installed
install:
  crds: true