# Production Environment - Full HA
# See staging values for reference
# TODO: Configure production-grade resources and security

tidb:
  enabled: true
  # Configure for production

valkey:
  enabled: true
  # Configure for production

minio:
  enabled: true
  # Configure for production

nats:
  enabled: true
  # Configure for production

opensearch:
  enabled: true
  # Configure for production

keycloak:
  enabled: true
  # Configure for production

prometheus:
  enabled: true
  # Configure for production

grafana:
  enabled: true
  # Configure for production

# Traefik - Ingress Controller
traefik:
  enabled: true
  values:
    deployment:
      replicas: 3  # HA in production
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
        redirectTo:
          port: websecure
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
    rbac:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
